# LuneOS platform config for the Nexus 7 2013 Wi-Fi (flo)
[General]
ShowReticle=true
DisplayWidth=1200
DisplayHeight=1920
ShowNotificationsAtTop=true

[UI]
TabletUi=true
DPI=323
GridUnit=10

[Display]
EnableALS=true

[Hardware]
Type=device
HasVolumeButton=true
HasPowerButton=true
HasHomeButton=false
HasBrightnessControl=true
