#!/bin/sh

# Ignore unused p2p device
EXTRA_PARAM="-I p2p0"

# Setup configuration for the rndis0 gadget network interface; it's MAC addr
# changes on every boot so we have to change it in the connman configuration
# as well.
RNDIS0_MACADDR=`ifconfig rndis0 | grep -o 'HWaddr [^ ]*' | cut -d' ' -f 2`
RNDIS0_CONFIG=/var/lib/connman/rndis0.config

if [ ! f ${RNDIS0_CONFIG} ] ; then
    echo "[global]" >> ${RNDIS0_CONFIG}
    echo "Name = rndis" >> ${RNDIS0_CONFIG}
    echo "Description = Android USB gadget network configuration" >> ${RNDIS0_CONFIG}
    echo "" >> ${RNDIS0_CONFIG}
    echo "[service_rndis0]" >> ${RNDIS0_CONFIG}
    echo "Type = ethernet" >> ${RNDIS0_CONFIG}
    echo "IPv4 = 192.168.7.2/255.255.255.0/192.168.7.1" >> ${RNDIS0_CONFIG}
    echo "MAC =" >> ${RNDIS0_CONFIG}
fi

sed -i -e "s|^MAC =.*|MAC = ${RNDIS0_MACADDR}|" ${RNDIS0_CONFIG}
