# Supplied by LuneOS, not generated by Boost.
#
# Boost.System has been header-only since Boost 1.69, and Boost 1.90 no longer
# builds a compiled boost_system at all, so b2 emits no CMake config for it --
# even though oe-core still lists "system" in BOOST_LIBS. Consumers doing
# find_package(Boost ... COMPONENTS system) fail outright without this.
#
# An INTERFACE target carrying the Boost include path and nothing to link is
# exactly what Boost.System is now.

if(TARGET Boost::system)
  return()
endif()

get_filename_component(_BOOST_CMAKEDIR "${CMAKE_CURRENT_LIST_DIR}/../" REALPATH)
get_filename_component(_BOOST_INCLUDEDIR "${_BOOST_CMAKEDIR}/../../include/" ABSOLUTE)

add_library(Boost::system INTERFACE IMPORTED)

set_target_properties(Boost::system PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_BOOST_INCLUDEDIR}"
)

unset(_BOOST_INCLUDEDIR)
unset(_BOOST_CMAKEDIR)
